[package]
name = "fluxer-builders"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fluxer-types = { path = "../types" }
fluxer-util = { path = "../util" }
serde = { workspace = true }
serde_json = { workspace = true }
